### ISSUE TITLE
Request for contact

### ISSUE THREAD

**Issue by axchanda** [yulin-li/asus-arch17-openwrt-build#1]
Hi @yulin-li , I need to have your contact to discuss related with VOIP. It's important and I would like to get in touch with you ASAP. Request you to DM me or connect with me over linkedin https://www.linkedin.com/in/rashwinchandar

Sorry for posting this as a issue.

**Comment by yulin-li** [comment]
Hi @axchanda What's VoIP issue? I don't think I am familiar with it as I just tried some demos.

**Comment by axchanda** [comment]
@yulin-li it is about a patch for wsbridge. Since you had forked it, and also made a tweak, I want some help in tweaking it for latest version. Can you please help me?
